### ISSUE TITLE
synthesize error 문의

### ISSUE THREAD

**Issue by yangwook** [hccho2/Tacotron2-Wavenet-Korean-TTS#8]
공유해준 소스로 train 100K 완료후 sythesize 실행시 다음과 같은 error가 발생하여 문의 드립니다.
train 환경 공유 가능할까요? tensorflow 버전이라든지 등등...
checkpoint는 정상적으로 만들어 졌습니다. 그런데 restore시 checkpoint에서 decoder_init_dense_0/bias not found 이 이유로 error가 나는데 해결책이 있을까요?

error 내용
==========================
2019-07-21 12:29:47.344013: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key model/Eembedding/decoder_init_dense_0/bias not found in checkpoint
Traceback (most recent call last):
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key model/Eembedding/decoder_init_dense_0/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesizer.py", line 342, in <module>
    synthesizer.load(config.load_path, config.num_speakers, config.checkpoint_step,inference_prenet_dropout=False)
  File "synthesizer.py", line 81, in load
    saver.restore(self.sess, checkpoint_path)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/yangwook8/.conda/envs/pytorch/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key model/Eembedding/decoder_init_dense_0/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by yangwook** [comment]
git downlaod 받아 그 상태에서 python train_tacotron2.py 실행하였습니다. train시 텍스트와 wave 파일이 다르게 학습되는 걸로 보이는데 이런 경우 원인을 알기 어렵네요? 참고할 만한 사항 있을까요?

**Comment by yangwook** [comment]
음성합성 학습이 제대로 동작 되는지요?

**Comment by hccho2** [comment]
train용 input data를 만들 때, audio와 text의 sync가 잘 맞지 않은 것 같습니다.
data를 다시 살펴보셔야 할 것 같습니다.

**Comment by great-energizer** [comment]
![image](https://user-images.githubusercontent.com/17938625/89155467-d8afb200-d5a3-11ea-9514-292a852512ea.png)

학습시 test의 결과(png, wav)와 train의 결과(png, wav) 파일이 각각 만들어 지고, 다른 텍스트로 각기 만들어지는데...
혹시 Train, test결과의 png와 wav 파일과 png 파일을 서로 섞어서 확인한건 아닌지요...?

**Comment by hccho2** [comment]
train은 teacher forcing 방식으로 음성을 생성합니다. test에는 teacher forcing 방식이 사용될 수 없기 때문에 각각 생성하고 있습니다.
